---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: llama-cpp-rocm-test

resources:
  - namespace.yaml
  - pvc.yaml
  - model-download-job.yaml
  - deployment.yaml
  - service.yaml
