---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system
resources:
  - helm-release.yaml
  - service.yaml
  - network-policy.yaml
  - servicemonitor.yaml
  - cloudstream-iptables.yaml
