---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: cloudcore
  namespace: kube-system
  labels:
    app.kubernetes.io/name: cloudcore
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: cloudcore
  endpoints:
    - port: cloudhub
      interval: 30s
      path: /metrics
      scheme: http
