apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-secret
    namespace: observability
type: Opaque
stringData:
    admin-user: ENC[AES256_GCM,data:Kf+36lM=,iv:2e8ikEwPsCgz2WF2Hx19Oa1TWzbAIapPfvdGzHBLceQ=,tag:aA1697UYCjNNLOQtJzY8bA==,type:str]
    admin-password: ENC[AES256_GCM,data:cnUmHaodTNaF,iv:1OpEccBNNuZLjAmBJFuMstK08VFLUyl6erU8mic9Zeo=,tag:I3PX3saY2M5ypU8OOt+xOA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1va7h9cnqt2gfhvy0pj947wmmewlahvj9j4zyzfznkpp9erf8xawscgft7c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0WXBRSlBNWEszNENsU2xY
            K1FnWDlPRGZxamxiYm9tT0cwNVo5cDNUR2lBCnowVHpyVEhBL0xvdTZTNXg1K01o
            ak9lTXEwMmZ1VVZ1THVtSUZ6aXhrMTAKLS0tIEF1MHZVWGdqbW1JWDJVYWt3ZWNX
            NDJUanJsZlZDaUE0RjA2UFA3cVlvQ2sKY2wCh9yRxWUvviWDxfHJNEg9BuDZqFwB
            sK3yTAunTvtv/DJ0QPH2BjuPI8PAZZysCgQVs/cXQukTAswnQkD1fw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-27T06:20:10Z"
    mac: ENC[AES256_GCM,data:BrX2FOF1B/C5zd90BNyAFBvY66Jbm8GOCn0q3Mt9p/Ke708Cke+Hh1a8Yfkgqt7kWoz9QrKHoh/fReTtD0Wl4kTxhpuVtOoDqEnlMYR8SbZpp6hZSbKSYERo3DkbvvPnIkjrlqKgy1xKAgAFV55d6BeG5ixCJ8c+Zp4+BofKqGk=,iv:lQdHPNufSMTSCo3vFNxPYsyRd7lMAHdPn9gGPirohxk=,tag:31/LunTIe6/Ra00LDhI0bQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
