apiVersion: v1
kind: Secret
metadata:
    name: alertmanager-telegram
    namespace: observability
type: Opaque
stringData:
    bot-token: ENC[AES256_GCM,data:wqYIhgd9t5ymj0yMitbljElnngE9Uo0wbEGgPiQ6yeYEZGIsASi/cNu6f9xdIg==,iv:Xrqd7BjpPWgwtmZP6mZcgmanZcJMBLcILugmHfsH0QM=,tag:oq26+G2bQ2km/FJq8U/vVg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1va7h9cnqt2gfhvy0pj947wmmewlahvj9j4zyzfznkpp9erf8xawscgft7c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNR3FpU3drdmFlNHlxNEFx
            SWRKdzFQT0FMdTcrRHpqWVpnMnZOV3hPTTI0ClovZkJCNUN0d1l1Z1A1YjRUbGJt
            S1U3TEdFTWl3RXBKbFZFZlo5aDB3OGcKLS0tIEhXd1FrZHNCS2MxRjBHNk0xTzZY
            TUJZSzJJR3oyRkpTeDVOWVFYbzE2cTgK34IS+7/0FfEHyd8+HJaRS4Sy1zUgXg4y
            vj5VU0EKTcH3pjPO1mCsqDLN9VoRXDiQceL+HxcAgNPFfX13IvXqOQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-27T17:45:58Z"
    mac: ENC[AES256_GCM,data:+zAbpyZB5TnmiWX3/hw4inEGSPtDn89JlRYxNPvB/bIe3Est8DuiF2mnvFHFkYipVUMf0fZ3qD+tH35WXDmtPip4nNPXNimrcqemd1TdzfrEya7WHUNfBTJB4bAwFManqW9XkjCPFcOPD1ehyBom2EZTejnbetq22goVUOfIpfY=,iv:eV3nxrGBD2Hy6WHBA6tSDw0Bd2ERI9kC1UwWFWsHn90=,tag:1vo0QLE4HV8qjJoBbC/8TQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
