---
apiVersion: v1
kind: Namespace
metadata:
  name: storage
  labels:
    name: storage
    component: infrastructure
    tier: storage
    # Required for local-path-provisioner helper pods
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/warn: privileged
