---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: localai
  namespace: localai
spec:
  parentRefs:
    - name: external-gateway
      namespace: kube-system
      sectionName: https-domain1
    - name: external-gateway
      namespace: kube-system
      sectionName: http-domain1
  hostnames:
    - "localai.${DOMAIN1}"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: localai
          port: 8080
      timeouts:
        request: 5m
        backendRequest: 5m
