---
apiVersion: v1
kind: Namespace
metadata:
  name: localai
  labels:
    name: localai
    component: infrastructure
    tier: ai-inference
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/warn: privileged
