apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - sources
  - spegel
  - cilium
  - cert-manager
  - gateway
  - storage
  - tailscale
  - tailscale-connector
  - k8s-gateway
  - cloudflare-tunnel
  - prometheus
  - grafana
  - metrics-server
  - kyverno
  - amd-gpu
  - kube-actions-runner
  - database
  - fstrim
  - inference
