apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - sources
  - cilium
  - cert-manager
  - ingress-nginx
  - gateway
  - storage
  - tailscale
  - k8s-gateway
  - cloudflare-tunnel
  - prometheus
  - grafana
  - metrics-server
  - kyverno
