apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-secrets
    namespace: cloudflare-operator-system
type: Opaque
stringData:
    CLOUDFLARE_API_TOKEN: ENC[AES256_GCM,data:X5+vJ9/J7BB11R6heRGpg4zU6mzw4o3qus8gkhlUgljfL4k//0iebQ==,iv:q8imgETx2PnEUeOZSvUVPTecGbLrbp8s4VNO72fdofU=,tag:grLKn441Wn0IdYCB/HyNZQ==,type:str]
    CLOUDFLARE_API_KEY: ENC[AES256_GCM,data:bbrChgCZsp2TLlQvzA3mBWzWHiWq2INKgNwftH7VATKlYEjpJom9Ew==,iv:fKKVe8bWdU44IpAUlNFHO7fM/Mbp+TD6ONX8TC+BtnQ=,tag:9xRP/LRwnljjgwzXXu2OTg==,type:str]
    CLOUDFLARE_TUNNEL_CREDENTIAL_SECRET: ENC[AES256_GCM,data:3GuVEx3zsM0VNPkvWIEfiZ8CVsbVmaamFeccCuI0F9uh65/N0wlb37uxD44=,iv:RFV1yzlR/sFRNPbNUiFLUeX1Sm3Ap4WY2cpCQ5sxhOk=,tag:rSooHpZaIJJzNP2dDpYw1g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1va7h9cnqt2gfhvy0pj947wmmewlahvj9j4zyzfznkpp9erf8xawscgft7c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwdEFzMlA5cWpWLzYvWmEz
            WVpPYmg0aHd5bW5MWXAyd0hNaE0rZ0RqWkZjCkdEVG1MRUMyczF2ZldGTUUyUnlZ
            VVVISWZRNFR3UGhMbWZ0eEowR3ZIVzgKLS0tIHNoZ2ZXNlhHZ01oMExWaFJBY1VX
            R1hlMTF4clcxNGZXSlArdGtXc3M3ZUUKzhJAL/4b53r4dwm8GruxMwtSTU2lrPEF
            atMubmZf2MCVKEiOb5amUX7mHczXS+bGyG1Mx+JMhmu+SyFPeNwW9Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-27T02:09:44Z"
    mac: ENC[AES256_GCM,data:KJRyw0Qc2L4fA3ybwa2v9y0TNH+qkmnNSev2RsohfaV/I3mHTvM2sXMqN30IPXGUHKIK4RzR7v8myPazSSINz8MtCeGypcWifpxoU3YV4gYbob53+unlRvQwWbEJQjwiw7xtP4QWmh2kb0RPMOTQkqOs1XVaCbMKHbYOh9fhe4k=,iv:9d1jp3Dx9KxhgeoPwIHCKCpNO+hHHR+XpwzRmnceDo4=,tag:UENLAE6YqpOs9hUvOJyCgw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
