apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-secrets
    namespace: cloudflare-operator-system
type: Opaque
stringData:
    CLOUDFLARE_API_TOKEN: ENC[AES256_GCM,data:o6N6UrqdlRc4QW/rRpIMHFeddoODIK9vUUxH7DzjC95LJLy/VjcOTA==,iv:QcV9rnqEZnvVQihcvnQeNpjO49PIwc+wqeZ4giUuxAQ=,tag:hbMavmFpuC24ZX4gHvZelw==,type:str]
    CLOUDFLARE_API_KEY: ENC[AES256_GCM,data:LS1XRYkNsKyAI4KvM86EQjIb/USKUkjdSo7gI4scSOZ11G9MR1WNKQ==,iv:9oF+9vN0aTPT6EOFKqE70pzS06QysoZVCFINwkFE1sE=,tag:nK11zVNFP1hDukfleacypw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1va7h9cnqt2gfhvy0pj947wmmewlahvj9j4zyzfznkpp9erf8xawscgft7c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2Z202ZFZmbm5hUS85N2Ix
            a01VelJiaHpiamRZZm9NRUxJM1NwMWhlREg0ClJvaTRLZDlJcC94aUw4ZFVSNFBS
            dFphV0V6c25lcy9JZHZsV054S2FHc0UKLS0tIHk3aWRDMkNkRFJrME5DTVdLZXRv
            TkV6YzhPUmQrdlJmdzZUaUM4eTFPZG8KTuHM2XcKIZewVzCog1UdQSNNDgDJZEWb
            S/wxxiqZbCtWQA1QmsMqFuiQxKvMRgm33N4Tt5VcFD5cWuHQuhm3Eg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-27T02:00:55Z"
    mac: ENC[AES256_GCM,data:8JpG2Mdn5RPDgMdFHLmuSQdqrR5F2paXZ4aquxXMiO03hlXJBcN/0n5kTggAv/BnX+rIlgSGpXnQS5+QdHdQAfeFXVnmWFz0cQ1+8ri8MceWM1IzNHwJwg4S1p9AElt64FRkB1JGNKzM72g03F6m9jHaynS77ZTVFCgL5vpy7JY=,iv:4Db2zt6ln+XSc6Kk0DT+Uw8DYuGcWTvNHTS5chVfa1I=,tag:8O/fviDOYQ0SiNbhirq4HQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
