apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-secrets
    namespace: cloudflare-operator-system
type: Opaque
stringData:
    apiToken: ENC[AES256_GCM,data:jnkGuwMRnPjRsw+gxRiD3PFowcrNFbMeh16RAQnIcK/qyna/otQr0w==,iv:K7khiivwopYRwkhgURT4IHdPA+sBtGZF7vPmiEgs94A=,tag:w9fzoVZHRbE4rW5d9+AivA==,type:str]
    email: ENC[AES256_GCM,data:tkS7tNm/xRiie4TAfqXZMc+weZfSJcI=,iv:BOPZfAELvdFhj8sJhPJVNfYHSRFb8iWQF0r/y3ekAOM=,tag:7Wn35xSnoRtuHmFk9PcNSg==,type:str]
    accountId: ENC[AES256_GCM,data:38+AtaCOtE27ypdJbCmhdBMBCj4GNrTeoIHodd9saag=,iv:3LAe2Yzbg1j9Ig9DNmYHOl7DI5fmyvOH5Wk2g6/tj6c=,tag:YGKLIG6Pl9rRnfORJvK0zw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1va7h9cnqt2gfhvy0pj947wmmewlahvj9j4zyzfznkpp9erf8xawscgft7c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGUE54U0pZb2NTVTI3NGZi
            V3JPTTNXdUNqTG1JUndtcmdNa29HMXA4NGtBCjdMUEZlQURnRW8xTy9tamNYRGl0
            TzY0VHNGbDVTQ1BxR01jTGlPMTFBVkEKLS0tIGVKWlBVTy80U0kwemJnR2ZlTXJ3
            YXE5QU5WMm43Ui9WZ0FwUWNjc3h3L0EKhCQdDBffJxBUr/JHafobzsq+9Cm7BGTV
            5Intbpt1WKB+kLBGzQCdaFE/ktYcuqGwQuhO6IfXwD2F9eQDq5QDdQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-27T01:50:07Z"
    mac: ENC[AES256_GCM,data:35jF+8+WaDHdEWN5x90girfpLa2AY+d7Jj5DPnjyYjBveTTqDnnwbKioI85wS/HQGBNM/Wj8Nlg64zSYegGRSssq/TqWcv1kxF1eTatkcxpzrpZaM1CDA0GCGHRxrHjUiZDJ9XS1m2iuzVYiIIB0em36tKuHP5o4GJ3XCgbrzws=,iv:J67Y3KS0VsUpVs8du/n+ezkN6WJ0QlXo5WqIS22RF04=,tag:F+CGZTRiHCma1UVigmc9gQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
