{{- if and .Values.name .Values.httpRoute.enabled .Values.httpRoute.hostname -}}
{{- $port := include "inference-model.port" . | int -}}
{{- $gwName := .Values.httpRoute.gateway.name | default "external-gateway" -}}
{{- $gwNamespace := .Values.httpRoute.gateway.namespace | default "kube-system" -}}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ .Values.name }}
  labels:
    {{- include "inference-model.labels" . | nindent 4 }}
spec:
  parentRefs:
    - name: {{ $gwName }}
      namespace: {{ $gwNamespace }}
      sectionName: https-domain1
    - name: {{ $gwName }}
      namespace: {{ $gwNamespace }}
      sectionName: http-domain1
  hostnames:
    - {{ .Values.httpRoute.hostname }}
  rules:
    - backendRefs:
        - name: {{ .Values.name }}
          port: {{ $port }}
{{- end -}}
