{{- if and .Values.name .Values.storage.createPvc -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.storage.sharedPvc | default "model-cache" }}
  labels:
    app.kubernetes.io/name: {{ .Values.name }}
    app.kubernetes.io/component: model-cache
    app.kubernetes.io/managed-by: flux
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.storage.className }}
  storageClassName: {{ .Values.storage.className }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.storage.size | default "500Gi" }}
{{- end -}}
