{{- if and .Values.name .Values.download.enabled -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.name }}-download-launcher
  labels:
    {{- include "inference-model.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Values.name }}-download-launcher
  labels:
    {{- include "inference-model.labels" . | nindent 4 }}
rules:
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["create", "delete", "get", "list"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["delete", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.name }}-download-launcher
  labels:
    {{- include "inference-model.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Values.name }}-download-launcher
subjects:
  - kind: ServiceAccount
    name: {{ .Values.name }}-download-launcher
{{- end -}}
