---
apiVersion: v1
kind: Namespace
metadata:
  name: tailscale
  labels:
    name: tailscale
    component: infrastructure
    tier: networking
    # Required for privileged subnet router pods
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/warn: privileged
