apiVersion: v1
kind: Secret
metadata:
    name: operator-oauth
    namespace: tailscale
type: Opaque
stringData:
    client_id: ENC[AES256_GCM,data:7DeD47iItV1wYuYy6xO5d2o=,iv:QK+y/E4VNqYCTymm7qMKBNF8o93tEC/rNOoj1fZ1zPs=,tag:7nJ/MuNZ3/tpXUO5VOq+Jw==,type:str]
    client_secret: ENC[AES256_GCM,data:aYFLjatrPa5PpBfmgkY9rAZnuG2Ny6ahxMjpaXygwHlvkqiIXcpXOs8XqP1J/nBSniwf+k1jbAMHy9pfo2Jt,iv:6tkzNCQFCYt3eAC/ksrtuSIhzpA3VCE0lyd4ld6hZNY=,tag:ZVB4XHDPCUSYyG9X1moxQQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1va7h9cnqt2gfhvy0pj947wmmewlahvj9j4zyzfznkpp9erf8xawscgft7c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmUGxuSGZTL3NEeTZobi9n
            enZ3VkowZEE3My9uYTNDUit0bmsvbnJnMHhJCmxOS3dnZWRoNGRVV3o1bW81cCts
            YzBhWkJUazVmVnFHcnNlTUgzSCtwRU0KLS0tIG1rajZxd0s2dmtHeXlDL0VaVXQ4
            ZnNzaitPNFNLVDhtb3VyQ21BYkVsL0kKGxbddcdhk92LHfDiE+IQjTkoemAhmiuf
            tEL35j2lZb7UFqgM505owyOQUmhl7LKSpeD3mOrssw3ZNoa2Gn5Waw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-27T00:51:13Z"
    mac: ENC[AES256_GCM,data:Izx6C8rHkeYoCoGBfLn9vMXRkaOv5bylIK7gx1dYleU33Zk/puI+SS1rYsCMFj0DtSvOLA2BWJ+/h5jFe5xBd0L3Kh93dvMLVQ283sLv9og7l8rTDzPnSFdmM1rJT9vpTZk6VQ+tUHaRAZ/3snZcg3FYopPGJa0GpVOXcn9M6rM=,iv:oRr9ek/7q1Qbai8nCPRU6mdu/clM+5H2nofT/uGaYQY=,tag:fjVBEPblz25zMr5/kklqYA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
