---
apiVersion: v1
kind: Service
metadata:
  name: talos-api
  namespace: kube-system
  labels:
    app: talos-api
spec:
  type: LoadBalancer
  ports:
    - name: talos-api
      port: 50000
      targetPort: 50000
      protocol: TCP
  sessionAffinity: ClientIP
