---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - spread-pods.yaml
  - avoid-gpu-nodes.yaml
  - cert-approver-control-plane.yaml
  - cloudbox-gateway-external-ips.yaml
