---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: llama-cpp

resources:
  - namespace.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml
  - http-route.yaml
  - servicemonitor.yaml
