apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    DOMAIN1: ENC[AES256_GCM,data:Lr80uJPZorbG8QZn8RLS,iv:C5pMe7U83Fd68JqAuOMgr+Z52fJPKAHrBchDKKRAG3k=,tag:bEA5UtaqZ82DQtKe/wW7UA==,type:str]
    DOMAIN2: ENC[AES256_GCM,data:vzL3xVLZpna+KRPq,iv:EFw8c3PzrJTdbnui2XTJkO2Oi/nlnk4v1GAmA22osz8=,tag:QFXQ8dURjS1EOcRuNm8uBA==,type:str]
    DOMAIN3: ENC[AES256_GCM,data:6DanG70QSCzE8seiwAJYzg==,iv:a5RTYGhuSdEuGGloqmcVc9BBurmTc0QL2XbdWUhb72Q=,tag:46OwqW+/zass/FmWC5QTIw==,type:str]
    ACME_EMAIL: ENC[AES256_GCM,data:64EL2F9jTNE0lzOc1iqQV3IxC6pq,iv:aiLWGawrI1Y+TzqlsHXri2kI0plxyeOEGghgOGJ1Ncw=,tag:kySAoVSbafVZBNpf00hYow==,type:str]
    #ENC[AES256_GCM,data:IEsGY76feQqfTDBZe9TMnw+Hu8hfX5S4Jf9KUpznQkhTzBciXiMm8TgoV/klFZA1,iv:nW3FjHoYtvelY/K88ULxKMTzpxL+v8olnzP8MFZ6CWQ=,tag:X4NO7RTPcpKgO3DthO889A==,type:comment]
    NFS_SERVER: ENC[AES256_GCM,data:+j9iJsO8DUrAWUc=,iv:DiRNhjXdFZViafAppH7lNZRcJPVcOi7DTCvP7tz7bvY=,tag:vB+c+F9M97fUCtZ1GtHA0w==,type:str]
    NFS_PATH: ENC[AES256_GCM,data:c6NVwZ9HcbBSZwE1vDUN4QxB,iv:zjwYfFbvFXyTNnkIR9GQ6Z0M+2IEzLkNYpuG83je1zk=,tag:5NLz9IpvGybcF+gxBrJVMg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1va7h9cnqt2gfhvy0pj947wmmewlahvj9j4zyzfznkpp9erf8xawscgft7c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpY1JCcDJDYVllUUtKK2ZV
            VHhrYm52ZVRxUDNtS0Qyb1BHU29aRFBUR0VRCjZ4VDNEQVZJVkE1QU5EdmFRMy9v
            MzJ3amszMWJBWk9IczNvSGNvNjVrbWsKLS0tIFlHM3k3amlEeDQwa2Z2OVZaa3Ay
            alRmOFZ5MnBodlpTQnlIbkErKzIyNUEK+6abW3dhbk4P41MzmayAfGdVcbc69p5h
            rJdKaaG2ErYKqn08gB/2Xb34JAQnXY+K9TKkNM/NyeS5Z0zr/2AaMg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-27T14:16:37Z"
    mac: ENC[AES256_GCM,data:9jAc5mxAyKGU4RheIKcbMo7a67GTV6UcmzvGWVhGmQOzeAs1amLannwtNFAmQ3JBcrMaJuAMwR4tWcukRyCr81BF2S+EyZpMY6awdW2pfm3fJyfaQEiWlanq4jUqqcHEZxaD81lTVXTIWODPmn0QzCrCjsPJpqOPI9EZ9TAcPUw=,iv:Pg7M4YklKHman148L6nzE9EneKvQoAhrA8XNXDyKu/c=,tag:lgwlKgZ9pmc/P4/IJtvrFA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|password|token|key|secret|crt)$
    version: 3.8.0
