apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    DOMAIN1: ENC[AES256_GCM,data:7Q1b2MmFuFk+VNKgdXwR,iv:Zn/HbfCm7l552l61bPtowFb18W3rAAAQWAlugwKKaGc=,tag:a4WrXqfIBPc0d0AE9ogHPw==,type:str]
    DOMAIN2: ENC[AES256_GCM,data:VR03GyeKbF3lnWyN,iv:4U7Sx4/kNma4Kag1UdHzCukIut+fRQjCVxeuD4DAWGM=,tag:2IpSgR7kbQNfa6CVk3kLTQ==,type:str]
    DOMAIN3: ENC[AES256_GCM,data:c+qMDsDW8QmxzJApZju91ZY=,iv:pr7uhRqAPooVw6nOiAIhV5LIv5unMXwCJajIyRujoYI=,tag:WqCPOZDgjCHwFw5C74amTg==,type:str]
    DOMAIN4: ENC[AES256_GCM,data:rrUjj+wLcWhBwqpLKhy3KQ==,iv:f0PR4+h9/r/Xc8pScrPplk8CkWshT0p3uoDGLqvJXT8=,tag:SSlKqgkPcKZYG35LYcbcjA==,type:str]
    ACME_EMAIL: ENC[AES256_GCM,data:dg2t69IGqO52fjOKrMvBHwumeLb9,iv:NjGDFoOjEzahRIBioTh2s8ZTTocBRlhCvg9CS87dCdI=,tag:EDZoCBUzWXfA6NEuQ/RcKQ==,type:str]
    #ENC[AES256_GCM,data:4L9FZmIlm+H4c0N+sKG3svozLBVPCN6hBl07ogerikaSDwAHBtJmqfUg1mH0acqx,iv:oATOm9MDY6TVmkCOn3u5GN5+KbePVfHXYwfI95d2hO8=,tag:4kpXDFoiM4ctc+nq4D2SAg==,type:comment]
    NFS_SERVER: ENC[AES256_GCM,data:tzdvvLad4AaS4NE=,iv:Km5N87/wnXtjzURERNkQy6PPgfqhRZbJ/VmyYEubvHs=,tag:hNA3jbml8pQjVWlLYcSl5g==,type:str]
    NFS_PATH: ENC[AES256_GCM,data:EtB82IEtuQqiZNnMzJXk+eWO,iv:7s4kzV2zhSNEnhNtWNx0uc6RGHbpHXvq6ERNXcoE/fk=,tag:7u1IZiwe6pCzmjOr+7I4dQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1va7h9cnqt2gfhvy0pj947wmmewlahvj9j4zyzfznkpp9erf8xawscgft7c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsLzJ6eHV4dWY2MDJ6bHJE
            NFhoOFhNZ3piNXVkbDdSVWttY0E3VlNDcXdvClRhbEVVYzJadW9zM1FuYzE0TXZ4
            N2hBTFZld0ttTzZZMEg4M3RMVjN2bDQKLS0tIFF0ekhldURkUkNVQkFRai9RWEQ3
            cy9TYUljM2JOWnVnQ0dhSHVXckl1a1EKUroK7xYokWL4dbWkL9rI4j2jYZOySoVE
            z5z7xfzdWAFxreRhxtTRg2f4z9X4oFAlKxSDwLZJPPB6W1V21m3lfQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-27T00:16:32Z"
    mac: ENC[AES256_GCM,data:05FVTyD5GyQFdpXY5AE0sDn01qEyX6SoWAkzQy532e0YGpuiUMboMEB+YvAb4fkuD04aJWyXDfYH3zQVg+XzoHgJP75HzmUdp9PzmtzGsWM5AceCVcprXPJ2qdyTIDpMa4ihqq+aaRa4VrXZLnGUEPRdv6M6kIgxzTAtlxG1vpk=,iv:xsQ9GfuvtYx232SgyjKF2g3lQ+mNcJCY1/65ehtWopI=,tag:v+dxfRFVOwZJoTI17q7etA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
