apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - flux-system
  - cluster-secrets.sops.yaml
  - infrastructure.yaml
  - tailscale-connector.yaml
  - cloudflare-tunnel-config.yaml
