---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: tailscale-connector
  namespace: flux-system
spec:
  interval: 10m
  path: ./kubernetes/infrastructure/tailscale-connector
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: infrastructure
  # Wait for the Tailscale operator HelmRelease to be ready
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: tailscale-operator
      namespace: tailscale
  wait: true
  timeout: 5m
