apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-cloudbox3
  namespace: mysql-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-cloudbox3
  template:
    metadata:
      labels:
        app: mysql-cloudbox3
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      nodeSelector:
        kubernetes.io/hostname: cloudbox3
      tolerations:
        - key: node-role.kubernetes.io/edge
          effect: NoSchedule
      containers:
        - name: proxy
          image: alpine/socat:1.8.0.1
          command: ["socat", "TCP-LISTEN:13306,fork,reuseaddr,bind=10.0.0.141", "TCP:10.0.2.198:3306"]
          ports:
            - containerPort: 13306
          resources:
            requests:
              cpu: 10m
              memory: 16Mi
            limits:
              cpu: 100m
              memory: 64Mi
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-cloudbox3
  namespace: mysql-proxy
spec:
  selector:
    app: mysql-cloudbox3
  ports:
    - port: 3306
      targetPort: 13306
