apiVersion: ENC[AES256_GCM,data:QcM=,iv:WVM5Z8L1ZduZNmLyHhsfzDHkkssuV7XVb6HN5FmGXck=,tag:7p7ZybLE16T9WJsAFP8tXQ==,type:str]
kind: ENC[AES256_GCM,data:e9iwYdQG,iv:JitxeKye8X5pRRQtXjBGn7sH+hurqcbOtUH3pmPPAEQ=,tag:gs/4yXZ093R3KNLLNp2+Bg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:NZo0jgZGyV6n4L/0H02dhXHY0mGc7DxZlGbs,iv:3zSXTM5a51hQdpNMP8aZjuveiEPjBNSJlBLEHIo2agA=,tag:cFt3zrijqW30KLlXF00tlw==,type:str]
    namespace: ENC[AES256_GCM,data:tUYVa6n/4lhpc64q,iv:8UqYFTJvfQjUk3Gkv9yWASlZdoLe786FvFQVLOkeQzc=,tag:gPozAKsZZrlxNSBz/a7l6g==,type:str]
type: ENC[AES256_GCM,data:KiA0lP7F,iv:IEvLEGcnrk1X//46CLlLCT2tONtI69TH4DZbwFp/2Dk=,tag:SWFkTkjCQ28M1yA/8rCyQA==,type:str]
stringData:
    api-token: ENC[AES256_GCM,data:zoGarQaGXoCBXgXkPzdH6bcOIvW/1h86yyNs/emmzJZ5Q9WjLz1m3w==,iv:5ffigGQknkkmFEXV9Vtt0sMuU4C5kI+gA9YiVSXtiEg=,tag:CBlt/2LN8IW3e/GXb5J/zg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1va7h9cnqt2gfhvy0pj947wmmewlahvj9j4zyzfznkpp9erf8xawscgft7c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhNXh2L1dIUmxIR0tLWkhZ
            aWRvOGtGVmtyNEp1TGN1UFh5NXdhNFJCQWpJCitrZU5qek9hMmg3SUYwMVBPb1FY
            eVJOcmFnK3JscUZyVVRrekM1eEkwc1EKLS0tIFNLUWM3T2FmelVKbjJGYldPTy93
            M1BMekxEdGtVU2pXc3FBeGs2R1c3NDgKrg4SdMiuMkzd6YlJjppjKkVPG7Yb5BUv
            X2IyDEyvZqhrGzUXV7nG8HZogXaztI74gADO/j68S74CdCl+zbvCog==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-26T20:51:04Z"
    mac: ENC[AES256_GCM,data:O0dk/GaePiRTCBu1X4Wm0TJ4HYy/RIIRNf3II1ujexf8looVKJFCNS4mt9ajz6guLnWwoX5ohEkZJXQlodXzFYDFOWqBTBQr/GspCtSBGxqGXw5kyIVsC2dxta9AQvVd992YqUNW124FqgDpBxEjxHhQCc8xpwdzC/F6dCt59ik=,iv:/hQshwgnsHjfRGULqMfm2YGoz7HzQwsOqeHyvWt9gio=,tag:9RLFph1h3shiP3L/I+jTWQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.0
