apiVersion: v1
kind: Secret
metadata:
  name: mysql2-proxysql-users
  namespace: database
type: Opaque
stringData:
  # Format: username|password|hostgroup|transaction_persistent
  # One user per line, must end with newline
  users.txt: |
    admin|4ST^%ABte7rn|10|1
    cortex|IYI9SCEeiFTXBYY0Aa1$|10|1
    marketbot_user|MarketProd2024SecureKey99!!|10|1
