apiVersion: v1
kind: Secret
metadata:
  name: mysql3-proxysql-users
  namespace: database
type: Opaque
stringData:
  # Format: username|password|hostgroup|transaction_persistent
  users.txt: |
    admin|4ST^%ABte7rn|10|1
