apiVersion: inference.eh-ops.io/v1alpha1
kind: InferenceModel
metadata:
  name: deepseek-r1-0528-8b
  namespace: inference
spec:
  modelName: deepseek-r1-0528-8b
  backend: llamacpp-vulkan
  source:
    huggingFace:
      repo: unsloth/DeepSeek-R1-0528-Qwen3-8B-GGUF
      contextSize: "131072"
      modelFile: DeepSeek-R1-0528-Qwen3-8B-Q8_0.gguf
      files:
        - "*Q8_0.gguf"
      tokenSecret: hf-token
  storage:
    pvc: model-cache
    modelDir: deepseek-r1-0528-8b
  resources:
    memory: 10Gi
    memoryLimit: 16Gi
  scaling:
    cooldownPeriod: 5m
    maxReplicas: 1
    enabled: true
  nodeSelector:
    kubernetes.io/hostname: shadow
  tolerations:
    - key: amd.com/gpu
      operator: Exists
