apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - command-a.yaml
  - deepseek-r1-0528-8b.yaml
  - deepseek-r1-distill-70b.yaml
  - devstral-2-123b.yaml
  - gemma-3-27b.yaml
  - glm-4-7-flash.yaml
  - gpt-oss-120b.yaml
  - gpt-oss-20b.yaml
  - llama-3-3-70b.yaml
  - llama-4-scout.yaml
  - minicpm-s-1b.yaml
  - minimax-m25-reap-139b.yaml
  - minimax-m25-reap.yaml
  - mistral-small-3-1-24b.yaml
  - orpheus-3b.yaml
  - phi-4-mini.yaml
  - phi-4-reasoning-plus.yaml
  - prosparse-llama-13b.yaml
  - prosparse-llama-7b.yaml
  - qwen2-5-72b.yaml
  - qwen2-5-coder-32b.yaml
  - qwen2-5-vl-72b.yaml
  - qwen3-235b-a22b.yaml
  - qwen3-coder-next.yaml
  - qwen3-next-80b.yaml
  - qwen3-vl-30b.yaml
