apiVersion: inference.eh-ops.io/v1alpha1
kind: InferenceModel
metadata:
  name: llama-3-3-70b
  namespace: inference
spec:
  modelName: llama-3-3-70b
  backend: llamacpp-vulkan
  source:
    huggingFace:
      repo: bartowski/Llama-3.3-70B-Instruct-GGUF
      contextSize: "131072"
      modelFile: Llama-3.3-70B-Instruct-Q8_0/Llama-3.3-70B-Instruct-Q8_0-00001-of-00002.gguf
      files:
        - Llama-3.3-70B-Instruct-Q8_0/*.gguf
      tokenSecret: hf-token
  storage:
    pvc: model-cache
    modelDir: llama-3-3-70b
  resources:
    memory: 70Gi
    memoryLimit: 90Gi
  scaling:
    cooldownPeriod: 5m
    maxReplicas: 1
    enabled: true
  nodeSelector:
    kubernetes.io/hostname: shadow
  tolerations:
    - key: amd.com/gpu
      operator: Exists
