apiVersion: inference.eh-ops.io/v1alpha1
kind: InferenceModel
metadata:
  name: prosparse-llama-13b
  namespace: inference
spec:
  modelName: prosparse-llama-13b
  backend: llamacpp-vulkan
  source:
    huggingFace:
      repo: PowerInfer/prosparse-llama-2-13b-gguf
      contextSize: "4096"
      modelFile: prosparse-llama-2-13b.gguf
      tokenSecret: hf-token
  storage:
    pvc: model-cache
    modelDir: prosparse-llama-13b
  resources:
    memory: 14Gi
    memoryLimit: 24Gi
  scaling:
    cooldownPeriod: 5m
    maxReplicas: 1
    enabled: true
  nodeSelector:
    kubernetes.io/hostname: shadow
  tolerations:
    - key: amd.com/gpu
      operator: Exists
