apiVersion: inference.eh-ops.io/v1alpha1
kind: InferenceModel
metadata:
  name: qwen3-235b-a22b
  namespace: inference
spec:
  modelName: qwen3-235b-a22b
  backend: llamacpp-vulkan-moe
  source:
    huggingFace:
      repo: unsloth/Qwen3-235B-A22B-GGUF
      contextSize: "131072"
      modelFile: Q2_K/Qwen3-235B-A22B-Q2_K-00001-of-00002.gguf
      files:
        - Q2_K/*.gguf
      tokenSecret: hf-token
  storage:
    pvc: model-cache
    modelDir: qwen3-235b-a22b
  resources:
    memory: 80Gi
    memoryLimit: 100Gi
  scaling:
    cooldownPeriod: 5m
    maxReplicas: 1
    enabled: true
  nodeSelector:
    kubernetes.io/hostname: shadow
  tolerations:
    - key: amd.com/gpu
      operator: Exists
