apiVersion: inference.eh-ops.io/v1alpha1
kind: InferenceModel
metadata:
  name: qwen2-5-72b
  namespace: inference
spec:
  modelName: qwen2-5-72b
  backend: llamacpp-vulkan
  source:
    huggingFace:
      repo: bartowski/Qwen2.5-72B-Instruct-GGUF
      contextSize: "131072"
      modelFile: Qwen2.5-72B-Instruct-Q8_0/Qwen2.5-72B-Instruct-Q8_0-00001-of-00002.gguf
      files:
        - Qwen2.5-72B-Instruct-Q8_0/*.gguf
      tokenSecret: hf-token
  storage:
    pvc: model-cache
    modelDir: qwen2-5-72b
  resources:
    memory: 75Gi
    memoryLimit: 95Gi
  scaling:
    cooldownPeriod: 5m
    maxReplicas: 1
    enabled: true
  nodeSelector:
    kubernetes.io/hostname: shadow
  tolerations:
    - key: amd.com/gpu
      operator: Exists
