apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: litellm
  namespace: inference
spec:
  parentRefs:
    - name: external-gateway
      namespace: kube-system
      sectionName: https-domain1
    - name: external-gateway
      namespace: kube-system
      sectionName: http-domain1
  hostnames:
    - inference.${DOMAIN1}
  rules:
    - backendRefs:
        - name: litellm
          port: 4000
