apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kittentts
  namespace: inference
spec:
  interval: 5m
  chart:
    spec:
      chart: ./kubernetes/infrastructure/inference/chart
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      interval: 5m
  values:
    name: kittentts
    backend: kittentts

    image:
      digest: sha256:967cbfc560c410478023e448b1a603a0d29d8ab32480949b055f59bca8a2356d

    source:
      huggingface: KittenML/kitten-tts-mini-0.8

    download:
      enabled: false

    resources:
      requests:
        memory: 1Gi
        cpu: "4"
      limits:
        memory: 4Gi

    scaling:
      enabled: false

    nodeSelector:
      kubernetes.io/hostname: shadow

    tolerations:
      - key: amd.com/gpu
        operator: Exists
      - key: ci-runner
        operator: Exists
