apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kittentts-rocm
  namespace: inference
spec:
  interval: 5m
  chart:
    spec:
      chart: ./kubernetes/infrastructure/inference/chart
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      interval: 5m
  values:
    name: kittentts-rocm
    backend: kittentts-rocm

    image:
      digest: sha256:3e10fb76973ca0940cbef7c9fa879e21ef14f4998c68bc5a3ed8635ca4caed4f

    source:
      huggingface: KittenML/kitten-tts-mini-0.8

    download:
      enabled: false

    resources:
      requests:
        memory: 1Gi
        cpu: "4"
      limits:
        memory: 4Gi

    scaling:
      enabled: false

    nodeSelector:
      kubernetes.io/hostname: shadow

    tolerations:
      - key: amd.com/gpu
        operator: Exists
      - key: ci-runner
        operator: Exists
