apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Add new models by creating a HelmRelease file in this directory
# and adding it to the resources list below

resources:
  - minimax-m2.5-reap.yaml
  - minimax-m2.5-reap-139b.yaml
