---
# Git repositories for Kustomize-based deployments
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: cloudflare-operator
  namespace: flux-system
spec:
  interval: 1h
  url: https://github.com/adyanth/cloudflare-operator.git
  ref:
    tag: v0.13.1
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: kube-actions-runner
  namespace: flux-system
spec:
  interval: 1h
  url: https://github.com/themicknugget/kube-actions-runner.git
  ref:
    tag: v1.0.76
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: kubeedge
  namespace: flux-system
spec:
  interval: 1h
  url: https://github.com/kubeedge/kubeedge.git
  ref:
    tag: v1.22.1
