---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: kube-actions-runner
  namespace: github-runners
spec:
  hostnames:
    - github-runner.whydontyou.work
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: external-gateway
      namespace: kube-system
      sectionName: https-domain1
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: external-gateway
      namespace: kube-system
      sectionName: http-domain1
  rules:
    - backendRefs:
        - kind: Service
          name: kube-actions-runner
          port: 80
      matches:
        - path:
            type: PathPrefix
            value: /
