---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: github-runners
resources:
  - namespace.yaml
  - values-secret.sops.yaml
  - helm-release.yaml
  - httproute.yaml
  - docker-cache.yaml
