apiVersion: v1
kind: Secret
metadata:
    name: kube-actions-runner-values
    namespace: github-runners
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:R9M86D0aVmTCIf4ctwaYGgyrr6zbsPKw0BOhcUjDLJbtF2LLj9jnl+7ZwG6DbzEL6i1pbWBONEhUH1aapot/y7CcIqFw0aIeX3wAe/UbovQHSa6MLShqA+/1Mnp000oZ8Zt+7n70bBEagK48IlSP/uj+mBL8WeJ/7NSDd9YsvydE9Klm6GXYgg6qqVp/lRf9cQDCzSNDiK1DDPLssjgjKgNrUr5uzVqtrHHNxmYzm13HTRzmzy51xa0o5wB7mqfDcdVc7/RzSX3DA/bc5fpEQnThOUvPtpX4ld9ijF74kBTNX4hlgGancRw3GAspyNnc0kLRAqZ9UZvy26RxJdppVmsQoT0q+O3fqxd+e33/670xyX++p+lqy+vsR9Kb0mUvMBYUa0c/s4hvARk65YXUvsJl5R8q7y9e6SSxfJasKF+YygEVxKehTAcFszMIdp6353RFO81+11pF+fcrIC+9PtcbDToaDdnfLQ15iVw9HuHHuE4NN2vC22gJZES416A4V6xgSPpBGFD1uE4cdfzmL4jhWPriQPYzYMZlot1KBSFK26rMtgRhZcGQ9U/XvgVuA+4qhD87p04DpAYJoOEHuO3g+knwKqrlrd616Li/TdQ1m0TlwIGCz+GJ+LMNjzOEzONjsWg3TWnSPSXFPsyeTf5jWZUvgDa0CtWby/A/D1WNKOe7l0qYa82LMjJYUbBBpIYaaDHYS2+XDNlbxnVt0wjBr5hH+To/V/t97JkobdGAJeKWBBzJLyumte+dpVxh/001D61W7wFBlHqXZ2CeYlIsBgMQWhId5u1ApeM76ilwcH135GqSlwH/QBhD0mTCMUvr5HJguMJhcOZrjDccNhACoJqz+czogHugsnARdaUpzQS8qiaFeZg2jFJKJCu2iRS0T4+/mORkAbqGPRQYaa1tA8qCv55g3+mQqgynmhtFwiSf0IBLaEFjaMRjPmKJ2ime6y4IWSQGrAG/mb7MavhDtJceEU3xBp6UEAejZ0/asBjzMqU5vPLSvwxum3sbpzvspl8oW4klWrdeFa3gKwdd3a9IEoS8MgMPDbV6JJzAXOHc4DbH/3DBSW5CcuQ+j8aucnLgDsAkK3yiAe3IDp1CEtxDZiBEhnEEwHdIOfwm4hnhXysz/dszdwnamXP2thPzy/ni62M0+7/iRzKx2RmqywfvQfwCKoFVmFsLLtO2CfhKMuqNDpnr6gwBKWpKZXduNW5TsfA=,iv:D4AVAT6sglYi+wbtrnIx1aWj7KOQ2OpIzzdpM34eLa4=,tag:2W2MuaIaku6hv/ZNIPuFeQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1va7h9cnqt2gfhvy0pj947wmmewlahvj9j4zyzfznkpp9erf8xawscgft7c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhQ24wZ0xCS0M5aHhtRWFx
            OG9pZ2ttR2tzRUNmQVRrb3habmNtOStxalZRCkJRWEYvc2d4STVmSElyQ2p1K3RY
            dXNndHQvc0tIaHRWUDZrY1NFcDdPeUUKLS0tIFFqbjVkLzRMQVdDRjBRL3BMTStz
            WnNFczBJTmcrcW5YbnhxU2hSaGZXWjgK9s96Uliw1MtuRKWTOFCi+6BUDY8nqrbt
            ytn6qAqNDcViS5JWK4vNmSTTvvLcRMDjwnyUHLeGt5y8JOAFiC5AVQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-25T00:08:03Z"
    mac: ENC[AES256_GCM,data:pLxQ6ujc/XG5jKM9zGj9W97CKIdhNsuTt8UmnFR1OVuMDYjI2OezXZg4K8X3+GlgnENYkUoiaS/iCYZXPMJtSL5dvpMtwzbgFxt8nurRY6IsvPHXSAHlM6Ox0vCRn+NTbxHXPa8BL7a+DIwTIuz6+MhJV2kRp89b4pxd3iX9TNI=,iv:5I1zNpjXvQuo5MIKP9saZUpwakKt+8nCpq5IyvAsDx0=,tag:HUSuH2EDF0wcwNu3wQoctA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|secrets|token|githubTokens?|.*Key|.*Auth.*)$
    version: 3.9.4
