apiVersion: v1
kind: Secret
metadata:
    name: kube-actions-runner-values
    namespace: github-runners
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:S8K4Wlz79o7hDwNyzm8hDyWxM5JScwstgXIIp2WjjYNJtoHojjB2iSqFkbu58Mr4SQf2eNOu/hTTJIUd9qb/SjPa/hqp/mFTlX8KlIkeIaNCGDkMWFtLuM9Pjz+mIuJ1im8ao6BXHXJ386RQHBTYNkJuEgzu27S/7QEEaW1uzhDV6raJYiVANSGql8yxThyJlXnIHbHsbUIfhxhV/fbrju5hIooVOFXB9zMuSC+2v28q8j8ecSXdksb2bzm+w+iERTYluTT4CZT/IR6Ua+xrGwobbFBw2YQdAKkkvxrfIjnQ1tpCw8nToz3+2nDM1OJBR+lzAMNPhrxZcvxVSllmq7xn+4ipU2XVbZSbBM4x0+gGp+r6V27oGXdblldVpzm8YX8NybQTLLzrsL7AIq7lPIg9ewyOwfI3yJTEVvGq15NmIkmC4KiAAjSx/e0P4GACIvtyahMi+A6T0Xex81ll8LiCJGpqXBiVp1K0maUIyfVaBzn/5Auce9N8Ek+II8+lfeImlSMdg/NPaUf0AnRLg4vMgoFMvEBJmgjLh4QCwIW5ET9uM+mPn1507OIZTE1G/ppmfdqf9d4TKP11pB4gE3XF9iWBfhH6S/jB19bFZXm3W214iOmFlon/YTYLB15c+1ihtnSjwCZlXxSHmZnyEbCMV5qmK0JJJieBc3O+kMkcnG6NFR3ml54r5KnPHq/x/XgfyiXMbYA9PxAMNLAEwD0H//bROHUNr7iJ8kSUqJ/Zfhyy7N7nNI1DCb18XkgKOme6bnRo/6nJlaohKKsWZWfIB/ngSj2JJ7s3eQ9Xx0l9A0JyJyJMzEKuAg==,iv:fpZCGiTid9JqgW3gYNdc3qAfCRlhl9xE0yjDHVxvYZA=,tag:qyQV9sFcv0JuN4Gkg629rQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1va7h9cnqt2gfhvy0pj947wmmewlahvj9j4zyzfznkpp9erf8xawscgft7c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlZzVQZzR6RWdLM3FER1lw
            bHBhaFp0bTVoUGVZZC9qaG92WWtiTnBhM0ZjCkVialVTMnM3dzNEcUc5cjYybVhV
            bytsSHhlYktqeTJ0T3NERFNZQ3I4UGMKLS0tIERVa0lsbnFFWTJKeGFOUVJCWUhS
            QytiWTFaWldrOGNwMEdXUEJFM25CNk0KeIXoBPPxremmUL3aJfKwvE5jlLu4+21T
            c+6rJFqZUejGxEC8k+/vO69oMzR8QdQNDL4x6edz/AMXpE0yQXjAng==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-28T00:37:20Z"
    mac: ENC[AES256_GCM,data:sQ5Z1b0FKsgNZUdMt6bq9cAtJ6xDJu1Md6Yt84d5Z8U9DzZl475N0sAbrQSy6xCrWrPSYkHPVYlPli+1rjJr/RtjjqvqZxoubbdY4gFHu+DVG7AG4D84iLAS5IBz24gTk5CVqleZYaOeRsLTy2bH7ZujUwyJ+nfCXE0PhOQ3cdk=,iv:fwtqwR41WhqstG+6rTQL30c2Q/y2kEF3daYQcLe3lS8=,tag:Mci86xYNnH3hj0Tzc19WVQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|secrets|token|githubTokens?)$
    version: 3.9.4
