apiVersion: v1
kind: Secret
metadata:
    name: kube-actions-runner-values
    namespace: github-runners
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:gvJD7ualOK0KU2G7wF6o7SMexEYpV7HLVbvPJl12zaFqDDnkx0bCaZdsQoslnS63nA7/WFDUUAn/eppRVEEKYVn7/ATVr/GcvohE0zFisoQ503oVzN998sQpUAR9BDXZoeQlcvdlvX4v/FFgFEZ2ecQkNAbAXQ7ymCIp9bzxqfs8l1iU4AodvONhRK355kkw0sokh5+rp/9S1S+mGQQ8d6FrG/HOKXu97x9yclC6bmrU/CjQJPMN2aYIIhHJg+/Gv0JFbTEN8OCTpvgN7Z6XiKB+7TzsGv3VDzZgYdNY4CmBH289fGM8MAabpVn0k9a9Ls8Yt3xGIgZhtAHFMKzIK7DUjtPo6hoQMkc/WWLdhOBoBnISpw3h+XSwTixDc56rhscQD3E7Y+3ObCJfbsVHyj7NJKVL03GsmWxEFENStfPcEDjD4OwhWDRfyb9aiwj5qnfi3dVThfGAV5+TpOiKd+LYTPvUN9nlfN2CAmyzB6ByjtIiH9PYbCiwzxQ1AzQ8JUe9BzzNSxFAf6G77pV9SdmwRvqSpvowC+4qI7k5qc1YHYOK65oosVKsrWEXCcQFJyRR+Xz9bL6yiGMq4Yrc0a4EhjHolj7CuWdmIZl/hM+VjgDZdaTFmm4E/UL8h0jPUtqVF/+AvpGTpgJHoe63ttVNo39GMHJkE6hC4CFzKUNFpCpRMWTvCHMh0hl8MsJyzGnTFWY7qNtn4Cuzj1zdW5uLactr4aFNLNAb96QHnmjM81omG+kAfBDnd5FuXXpNZLU4CEK767oEKNVoLlMfvn0q4ymN2gyiuuSecTUSAQsJCTyyQrHkPndfOusbu/oj59lZy33x37ENeCkiwzn33LwhthGvEmOtghYqSIW3gcpbnkBbLMs=,iv:MBeXSlAsvu+9x7+Bplny5Rjhen/8F2MKQyYhHrPPI0I=,tag:7UoOG1Ijg6cGHGIrS1QxJg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1va7h9cnqt2gfhvy0pj947wmmewlahvj9j4zyzfznkpp9erf8xawscgft7c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvSjZTNnUwNWk0cjh4alVI
            Tnd0RVJwTERFM1k0RTBpVEFOTkt5YXZUTTNRCmRQdVdSYUNpdkUwZDRnRjE5T1FL
            WGxweGFxZ3pWbFhCMWZoYnFxUEZwTEEKLS0tIGgySU1tRUtOWjlNcVdxQS8rQjY3
            b3F0S1VOc0tDaStKNnRiQUxMZTdNRWMKuyWjZDjW/iwBSRiA8JiMWfuhDlAmJLD5
            3+mNSh2FIwSFq7ymZJha1cupQm3mA40qoEJ5puuHpUv0LPfUDEZaRQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-30T15:36:19Z"
    mac: ENC[AES256_GCM,data:UWSBTi4DibEx4ZCwG40jhJSV/PIDucxwQLx0so/z7XGz7a1nI+DkWR2d4ZANgXAVSVsfwlH3P7IlViVh/qp94hqDEr3OMhmB1C4eQD0vuZ1vf6u6rBL67lAFzBG9ZUVXiTS+RFc3hsTxZ2UBRfCvJf5KFZZ8aG5mH8GVOgCMcKI=,iv:jyT8sMgBIa4h0Axd0BJ1uCcbThIFYw9mrtF6yXYedv8=,tag:gd0wPNSMPGWfYcatPTFVvA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|secrets|token|githubTokens?)$
    version: 3.8.0
