apiVersion: v1
kind: Secret
metadata:
    name: kube-actions-runner-values
    namespace: github-runners
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:vufzsfKo42JKZqCkl+P+5f1fO3iwNXv8I7MPbEUMI43eEcMCCHuR52gCsBoqnfmW+kjvzohi+vL+nca/ZaOlDpP8axgZgs4E/uVkN2AVea5bsCUUchxQTQemmnxFWiweV8iFRsQ+9QUHZhkNjUVdtzy90U/3aULbKcm52jshIuhbh7djB5m7jPfTHvQ3AcEhJAOtsTPSF3p/q7nce5x9X7fwYF/H0pCWTwCrIw+lZFdO+DtfzrOtRWv6paDC3rVN7HBsQxKRSrYJX4lbp3evrfyUKJMJz2sm3XM5ko0ZgkozGaDNoj6xWcCGPuNXIH3RDfK6xgBQRQa6UKQHmLS5QuJqbYaVyCJzAAbyhtQpJT4+LP9/EteHwxZdQ2NZ8S4UuY0i6DLcvWePBkMljeChz4TXgHLiwQE9NbhZrt27DYB18w3Uw9LPArWMRFPa0Mrx7iegPzUki/IiCXkWWOilrwBtZHNCwd+k5rPkDMu+zWWgpptVtgAhnyOmnj6wD/nCcp8q8YpBB+M6+6T89b56uQDsEE1clyK22sVi42peHAshN5XrobdNcvYLhmLSaZc011EK0FQtXWa157xqIvoz4weOiUGSTdY+EsKODYQB08RB03NCTolRgCoHU5bQgaTncN+3zA/awNtjfSS/TDAXKn6ZvZf84Qm4Fa22XDMd75h3jpFC6aSDCIbXX/RnIzMiQpDEh9Llq8/Z2ri43FR4os+KVURUSnnDwL9zlO57d4cGVLV4XXrjAzRrz64VxyfsoINc2xIm5bIFYVJNpAgOIWhQfSyBHM6PG2kPR/8zmXbMxpZZUYuNIwajC8tkOK8xOD+ADUZjn9R7ej1/CgJM,iv:Z2OahE3yQvEd0qaj+eFmyp1OUhF3Vm2K9w52eyCurY0=,tag:lQYUCD4WB4ClxaOcmwHykA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1va7h9cnqt2gfhvy0pj947wmmewlahvj9j4zyzfznkpp9erf8xawscgft7c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxWjVFQ1JuNjJQbTlyQzcz
            VGRLcmFBbmJwUm5hNEpkUXZpWG9DNndiNHhVCk9pMzVFSVNFemd4MEVhanB5dXQr
            RnVKTFJHYUJ0OEhZK0pwdHFieGg4dTgKLS0tIDhmNnlpT2ZBME5GVXpGQ0JOai9F
            TEprbHZkZjBCNGhlNXFoSE9HRndFVVUKXu6WfJKSpADLMpBZ6eF5S/VERxesvZY9
            7oSXhQgnlD2F+CD3+Q18p/Zm7aAMAgBEoqP7l1pEwIuQ/pwKgf1ewg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-30T17:54:37Z"
    mac: ENC[AES256_GCM,data:d4EduNmZDuskT12cZ8C7lrRqP8nxskE9icPL3RP0B8fX2jDT6dX7W5FjWeK9Vz0BI5FkaXzq1KwkIo3h0Q+SlpUaOe3/gTRGfHmOH9l08akXfK8F65DCGtCqBtlJiF27mBr1zp7F5GVFgRxx2IMnrz6hOfvG56g1z2YrvkCsPvU=,iv:CBrqY+V05NoUIaEezSd1HWJHzpn/Ru3AvPf2S/2ZEg8=,tag:H++7tBIw+Omo+9XgiT7+Aw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|secrets|token|githubTokens?)$
    version: 3.8.0
