apiVersion: v1
kind: Secret
metadata:
    name: kube-actions-runner-values
    namespace: github-runners
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:NAZlDQIpLlRMTt9I23BNkTydulycS2Fka6l4r2uqMGZ5gM/88sz6GdMya23kPO0YChxhMpblLiSNGjltksE2bk8Md+ygj+MTURjg8hdrLtwQ8wQqsTpeFQ8laGDVTF9wZ1jHRruGuH8XDkcXDNvMNnPzCCo5S721x2qX+D9flhXs1EUKJHCURy0CoDpKGuni19PhghqMcU7oM5NC1x4KK2xxFpY8ev1DSkDLH3IA0nlZtY3irP4Znbo3tiG3mYsdODc5XyiOFbXHNTEpYO0kj1+q19szBlfx12YBVJbhzyuvFgPzKZVPdRsnH9LXjQIMIpWAH00L7V8IgzDKrqFmv7N4+IHxptK8md37Bk1eKYlqQDR7j1A8LJHZJ6blxpheMb0zWdFIKen7mv1HSgo31qx+u39lvPudG9Mk4xnvEkDp3wyLEWv4nNnVQShXbj3t9j2xvO0n0oMNnN+Zov6frf1WC/FAmBuqVHF42q8T/a3pSDi3mSUINmJsHVoPF6rr7lR0hR8u94Y7bJUDFGBjMrm1k829GOoGASJM9WPq+etbvfEd2XzykJmhOY75iXQwoqmp2eYiXI53PnEEjKeZjcLhWlKkIfZA3tvbMS9bvzwVZKqm+/Ft0DzrHroDvCZNbU1ZDFKG8ZzOwhaTFJYBXkooPMSxkS1vVdIM8eH6YPLhvlLqhGWXbiybtWIIxzbqb2xC2oEdzHXGH0e+bgQzh0cOb9rX8VPmnnF+98UMlK5QqWpintZqmIjRG64//nq9ES8g7TNR2Zp7hPQiFFFxw8veJvr/Z4NEk4NxPutmQjoYkyKnPF/AmWuMESd7IRnEQGFueskKaBcwkGLESYbs/oZXw+3ohlr4QhIy8pAKfP33haTvFnSzXK91UuXblo9vlbr93KlgZXZuiDM0boFVP3iVOpu6xVRX2xzWfBuadyrzsISvQmNNeUBM+NsOhKZNgiHUebpJJHIiy/IFS4mm+2ri27dQZTPC5MRpMWk3NA7oExzmarKbQEC3W9ar3R8VjknC+GRzI6BUf9HrfsovPyv3nDNcFkhmS8Oh0WloDagSZBfeEtVqPx7ss5xB3RYFADX4KMgCB4XJ0VZnG4oWt6dpsT0FEf1LHIgyusxgv1cseRoqxBf0J1fn7qslRa7N9ZOw8UPQNtPgb7BM8Ba5Z/z7dHgoWMvI+miN5bRLT2dEZN/EYXJ3G4dB3g==,iv:p9g5gWTdpwnw/FudlRKP2dV8qW8KUYQjECyf6Z2ME/E=,tag:o4EpZfoj894JXmYk7vfGjw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1va7h9cnqt2gfhvy0pj947wmmewlahvj9j4zyzfznkpp9erf8xawscgft7c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHaVJrS25VeUZQaE1DczZu
            R0djV0R0dXB5QXBrd3phOHN0aExWYjk4a0U0CmN0SHVrY1ZHZmhJSDZPREdHVTlv
            c0EremJacm1tRURUdEJicHFCL0VSTzQKLS0tIEJySzhyVVQvUy94b2QrY3FDM09M
            ZTlmZ2VpMkpGWXNGWnpFcUEvN2FSMXMKyka4Xto66VkmsiZO7xZC3icXicOau73O
            UTrAHfj6NMkHQ95FCSn4nyt16gK+IW/Td02Ved3b3UyQShxqcbCA2g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-24T23:31:52Z"
    mac: ENC[AES256_GCM,data:EFfN7KK7QleX5+QDaYHbDUMw9t2em/TYZ921EYck+RTC83dNw/5invOzNE01hq/nETETVzzcznTSRBN634sWVsdRTmTltQcCkc1YruLjyfrSweipXVxPLqJn99tBSgqgc5/NMRXA/a67bEHlFsyUsPVmx+pdpmQWHNx9EuM/2fY=,iv:JIxYXzev4vTA3K83yRs1P3rwGy8cCBqNTLbZM/36PDY=,tag:qF2GNznxc06vPwqMZ0ynPg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|secrets|token|githubTokens?|.*Key|.*Auth.*)$
    version: 3.9.4
