apiVersion: v1
kind: Secret
metadata:
    name: kube-actions-runner-values
    namespace: github-runners
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:p7Q6xe9ykYKvBF8nl4EJ2a4GC0pBaK3bI1Qz2IMAeeFdQdeez8/u5nF8A9OdX6PrYvYaRu2WaErT/oyWCCvOWSKk87/ZOAn0pNtZh4qhvTR4672LNU+Pxz6JDmC+qo50VQlenmq3V7M1/BbGrsx3uV/vIFm81hqPUX35Cmj1IRFVIwM7gq8Cta/8HVmyDmkQGxLDpyd2HJoAJEzrXrXfHo/lNOqpdfC+QaXpP4q+wJ9Mhoow3kyAfzC+2SK8U+D98/dmubYkTURJnLnFoKQv+hkrKcGSfWMPZ2hiRIghZaPJYh8pehq+ZtYKbW2wjDMyW4i9u3PEI+cJNdg/rj2lJfdymR2zsoMNo1H/p+zErXkHN3iRXt/BDum7PeYXBIWBJCsZPh2Qw6LSMJzqcsC/PyrVwHi36UsLY0xviUmpBT0FhtNH/SLx0zoNDpho6QhrRrOKcR53Q2ZaCPIZWYgs66VAYe8u2Hb0BJAOSdxepMUuzA1/0YwJTuEnVA0vnt3xDa31sOI48VoDAOnsaDTIbWoigJu36Z/tvKNB2MepzaoypHCFsRtoGuuvIm6anysGOJ5cUchgYI43OzIlFJY/Qpep7iK4lixd2x6QUluY1sGn72WfPDT+lFxCVynoNkXpU/tqNU+6ChqbSXYRZw9igT+aIs4orLbI/H5pvreWg80UJA0hE3sQyQWmR7CSuWx+M49SccLloHZVIx8IgW8teE2IRg93MyuFB1wW0q7+UXA0CsynHODlYFAWmq2owte9za/dve9Rwa5gaPHRByKIcISodWGUSgW+LjUQVfAkctiRK5yDv6GoRteMyKqtLa/WlLOAB2XVechxdYlghdgM,iv:NihZ2fpbBkf+yRICGdod126ZCQwghERNuzlV4x2JFns=,tag:VPEKyAOwMP84YOohGx4oJg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1va7h9cnqt2gfhvy0pj947wmmewlahvj9j4zyzfznkpp9erf8xawscgft7c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvSjZTNnUwNWk0cjh4alVI
            Tnd0RVJwTERFM1k0RTBpVEFOTkt5YXZUTTNRCmRQdVdSYUNpdkUwZDRnRjE5T1FL
            WGxweGFxZ3pWbFhCMWZoYnFxUEZwTEEKLS0tIGgySU1tRUtOWjlNcVdxQS8rQjY3
            b3F0S1VOc0tDaStKNnRiQUxMZTdNRWMKuyWjZDjW/iwBSRiA8JiMWfuhDlAmJLD5
            3+mNSh2FIwSFq7ymZJha1cupQm3mA40qoEJ5puuHpUv0LPfUDEZaRQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-30T16:33:36Z"
    mac: ENC[AES256_GCM,data:gQ15EEHi5dyOm9NrTM3PrqxD0Xfl1L1xysYPKLgqE3t5Prt7cyACwjqRy+VIrjaVCmU9QMuX1tgbQZpvAbFzMGFMDuK/9tVm6EzESvXVgwtJH2UbKh82+SDTBAXuqrMPcpi2Dxb3mJoRNIhhO10M3IQuyXDEO9uUqO8b2TEZ/5c=,iv:vhT8ShGSFuvjUedg4+ekLoUMjavR2LxkcylLLNsv7as=,tag:xzv7rf2ASiqJ9SJ6iRmmCg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|secrets|token|githubTokens?)$
    version: 3.8.0
