apiVersion: v1
kind: Secret
metadata:
    name: kube-actions-runner-values
    namespace: github-runners
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:KMZoZWd8v35A6fYlxZGtr1GXT4D2Iwarr8gDwwl61SREGvuc4iTctuEnm5vxeq3M9u2WLuR8GX8PfUV11WaVPlvAhL3AO3aNLfeZl91nbVv6p8Zl2A66wQJojnSqrl1/v4y06MjK+cVNiXxMxkzCweyQpgKYHfr9NIjfGuqEy8WoKAj7lQJE2TukaUZV+FvvZ7bcQvXxLLVnC2ucM93h5O7pI2PAQJzGfVny5SnUOYyKw4GmRWl0cfeS92sV6tJ3pkeE/kfYuI0OqaZZIICiAUMW9tTm033GW+PnHvD46/KHys+x3Ex2q+zxeqOJSuZfEw5ESOWnD+RO8YnyTzKK3ez0XBhzMWaQksRE7hEcF6c7lg4iGmw6pLA+wx9/4RnjqoU03IzZiGJSHUdXVpsNZeiA3GMXg18GvLo3qHswLttiA0lsnoGeC1ypyc1GmkM7KpR1TGSmsLcQjVPSIJVFgP0lO2d3reeZaLv9hA2B3h1bqHjfgoddM4uLvddOUaVlZ2Fj/ch+Ow1D6ld+ClkuHzmkZtafwg9yEdi19SMaOcLAHi4MLcxisz7hy/W10m8rzMQLwj0ICJ3a9Wi0Zbhy1UNERV6LY2hokzPIG37+H9otiuRtFdRxpm/KR8n63VIe9IasPygtPuC5xnBHyHqwT52sAtxJ1XR0d/sWX590AjuRrZqvw+2o7TSWEqikk2MhG3cFlyMIVER5yZb/4OJNnZ6n5AXEwmjFp0+ucos=,iv:EfurjGWCiz07IcbA2VF+61LqppjLsNvJSpAD9p2LlBo=,tag:ol6GymItNy9bgwhp/Y0UAw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1va7h9cnqt2gfhvy0pj947wmmewlahvj9j4zyzfznkpp9erf8xawscgft7c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByVXlWRUtlejMrVUcwQ29J
            RzVzZGcvNmVaSzQ2bHJzTENadEQ3OEY2TzJnCm92clRiUllYZ3UxZWkyZHpXMWlv
            YlFuZzNGZnBzcTVYZ1RIbjZVcS9ELzAKLS0tIHN2eVp0UkY4TDFwZ3puajdtMHhO
            YjFsdHhSMXpSaEM5Wll0TnFnTGxSRGcKvuTaqvirSupWQc5Huvmj5tJ0I0JFTqgQ
            DQ2v9q6AFa223he9pIc1R4JIArc6Hjwhb15wyToLZ1PxhRgP2yEKWg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-05T16:48:17Z"
    mac: ENC[AES256_GCM,data:RbFgrpt+Y5Buv286CUI3xPGR3AfCh7zpUOqvBxO1v+ui7TO+6KfMbGNKC8iF+aL1iUo5Tzda9EAkH43UXTbj2IAJCSls3Nn2Y4Q8kaaEQKt4Vje+2wVLzpbhYQ1wAiJkqVBCP3+XR7u7o5zh1Ox5HzZfYjG2Dnl2F6U9DAodcWY=,iv:n9bO0zlUDEM3EJfEfHG7hrzJSeqVk+h/fNoqf04uQ5Y=,tag:NBlU2fn1mq6/rgsyGoJDbw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|secrets|token|githubTokens?)$
    version: 3.8.0
