apiVersion: v1
kind: Secret
metadata:
    name: kube-actions-runner-values
    namespace: github-runners
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:BljAtaH3rPRoKUr1onKdFmyMXONdyZORnbHBpm6lEMwgN4P8G/fpQT6wwcITlEfqbQfk5TzKLdlJRbZ9gHUtYsZKukoRnkXcBM6OK4sXrlbDK1L9HWubOXfeMwD246ZPcKlvVAOuT7C3XCSjNzQA1ENx9U7nG5a3LnAn3EcgIrBJd5yWOXrd7YzjfvhM9Fo5jN+FhjjiJq73aBdcV2iTYThVaRYs2O7x+5FkIGWcrgkYF/U2jQeydWb2O0Tx6xtVAPBXDazYRNqX6HkuQSxtZXgR9L4Y1OnQMCxKYf1D1VU6WOUHYnJBtv8whUnorTER4OGA66j2cs8kGFfW5z+iqLnE1B8mIu/Xpuyb0M4ZbC4Hs0JtTw7cVoWV18VyPsE1O55okwy6VFuQ/xaJRx8r0fgoKU0be1cJKmNUPZwjART1QO8LnqTRG7dSzYu/vXd4gLKixollDvNkVkUk39K40Nmj6tUATYXq2QBM4/y2OyKM13wPLSe1PavtJyezSLttbeyJcrAs+tJNXf75e6hlOQLSiYQ50bt27I06dBPutP9fe08efoqty5GwzwaX0nXZUaSNW/lxF85V+GCSpv5QBVH+upherR1oLZd4aUgjg8MJvb89Zf7Uq2gydxeP7AT8N4uhf1Jg4k3js3mHY15yaRdXTonZHwOPgk9lvNNimY5g8zuUzYU46TyQEKZMA4k8EVyLl8II7HR3itBxQ04lHUvlmi0djWDutqbf4rnWEkAA+WVLh4WoJS/u9JiwrNTqUTzNu71yG8jObcRVcpCGI21KopC6MH0lRY3Svp5+NSY4PZW3J+wXGDITpBJGXInfK27PhVw8Hxmu6mjKgjzoSadZ6zaBl2HDTdFIeOtxOByKnrbR0aW7M7pJFazx1J6H/Glo9EZ0PZiQyN34R3tH8jPlaMb9VMPcLjlc/zTUPKCFuqcMioGm8BHGHUlOOTU8iUc1R6pQk7c1NehKJeuH+cVlUVJ1cjlLFZewVLpGcntnG5qYypNo3+wgYmTAABGiHNYS4QCY30JYoEt6trKo2Ou/EiVb3oFtV2CXt1cFsHJnOLi8XHkZKDAJuS9fea3++2AZ,iv:MEx/KSaK2Z0tjpEJoPJwEDZRvCSdNMAE4u19hDGkrjY=,tag:aoghIxhTyiXlZiCSfHVvVw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1va7h9cnqt2gfhvy0pj947wmmewlahvj9j4zyzfznkpp9erf8xawscgft7c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLMGQybEw2NlgyY0FOT2FD
            Zm93dHFuWlBRdk53ODZ2ZDNsMEd2NHNmcmc4CnVrcDVrYUNTb1JhUmRidC9uOTUr
            dHJnS3E3c2puZ1RzMlpwZVdEd1YvL0kKLS0tIGlCbjFUTXRtTGtsa2Z0U3p6YTZS
            NDJ4RnJOMDhWM3AwNEdQU1VmenpkT0kKHaxfZ0hrZzWJCRVAJ5qlaw2iS6DV8PGo
            aU11+XhsqycFpvcCutHibqT6yCMpoTSF916go3EmZi01mz6BH4B2VA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-11T03:50:04Z"
    mac: ENC[AES256_GCM,data:KX7+dUGgDvb/ZN4V2W27HOZ4KdTOr+Vta31kAYC6rkQ7T3qpcbkHnz53iBpkVUUfaBJV51ok1S6sRyY1Hay1xKIm+FHpK/6B1KoDnjbbqolob8NJmf1mqoSgwSEGIrKkyVNb18ELz/egcy5SlBB4x4flmFJdRtvNTwR7OJxu+eA=,iv:SCJC13qgTvUSdH0F3vMiGtcYP5b1pBvfkdoKYEjlSXg=,tag:kHad1Vv5J1z4Exqk9Xwasg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
