apiVersion: v1
kind: Secret
metadata:
    name: kube-actions-runner-values
    namespace: github-runners
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:kLyalzo54htm6tI+nAlkZj6SFA5IuhSCMZdo/pa+bJ+OfIHOjA8j6vrhbOYGD1INgw56ohnkO+5DENenZiQR137yeIXSOncZ/gaq5Er1AfyqdKcB7QAziJZR/QTqDw+GyiJxSRmYHvTbhZgKb2IVnOY6IMbSWvxCb8BIaF+p6Tex2cBbGF1GipHS32pIAf0vgl2hMn1LCO9XQRYppIW+unEuYC49ILv3zxB+qUhIMqoVuk5bGbz3sXEAt/SklswW5FIOoAIJt71/hB2UwWtfygmEtE/Ui9+CaXBcX2/ElRau32YG2OTshznHjI39rY517OIDL+G9o7YnoF2O5Foi878Fs89E25zryy3TnJa2Z3FN2MvfFNniXMyTWBQowEJiq7Z4NZTp2IIx9+V5GJQZg8Gzd4cYyW8AsuHiQkFRLe1jOklR77dpA9kQkIMaZRUnqL3aYzTpp8YsMXh0Jveu2NQtjz/OiRf+216zFMn9mOigTMnpoykaZW0DbVOn7Yvj2IMTjVhhAdg3DEFPCJovpulAQ1Vz0SUJFlJQ8wyF5iI+Qz88y9zn2P/ocz8OQ0rfD2Oi+GuNFHXicr+dxZTXoHR+CwpQFF3laCMORhDV2C5C9LyfbrzkONAcxyTqI6gkkI/sQZDobtt4nSUefTjQo60hscaJQheaP1hfJg8T8FPhUijJU4ccuj+YJqVopuJc6mt5E9i7olmYzmAEEEvZZb78RAww2b6jtnAsSnQFe5yojwjWmPBiR4KYOB6Yb+m06Jwr2dfsV9/pRG4t7tAkWU6d18559VU3GaQiymY9HAvX5leod9fHP2xemRYimQVyHfUpXV9u41VCsxv45oZE4KAXchLMCGDX,iv:pE5q3V4wdtrpMlnJxp+6qAXBMkbQzwQS781cjtvTF7I=,tag:st9YFftZDgP6Nw615Es6Ng==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1va7h9cnqt2gfhvy0pj947wmmewlahvj9j4zyzfznkpp9erf8xawscgft7c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvSjZTNnUwNWk0cjh4alVI
            Tnd0RVJwTERFM1k0RTBpVEFOTkt5YXZUTTNRCmRQdVdSYUNpdkUwZDRnRjE5T1FL
            WGxweGFxZ3pWbFhCMWZoYnFxUEZwTEEKLS0tIGgySU1tRUtOWjlNcVdxQS8rQjY3
            b3F0S1VOc0tDaStKNnRiQUxMZTdNRWMKuyWjZDjW/iwBSRiA8JiMWfuhDlAmJLD5
            3+mNSh2FIwSFq7ymZJha1cupQm3mA40qoEJ5puuHpUv0LPfUDEZaRQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-30T13:29:35Z"
    mac: ENC[AES256_GCM,data:0+S01doB+aY0YD0GBdqq38EKpGzHXu4JGNxgKeHgXPZo4GcGS/UYLXnnpaZAQxVqVpDJWGAfg2MRb85W0MD5Z0HcAtbqlKA6bGjTR6z07DjtNIW80Ef3WQMylZ1GGnR+T9YuTBBZ8hdtmBEMCVsu7ZKbrLXUPoH2GjmCuIEdA/w=,iv:8ZfqW/gUJIOpl3UTB7CD3dGSFQDwAQf13TXPkhQmSBc=,tag:ku2vWJpDoy2M57sM4jXQsA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|secrets|token|githubTokens?)$
    version: 3.8.0
