apiVersion: v1
kind: Secret
metadata:
    name: kube-actions-runner-values
    namespace: github-runners
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:42+ymBwrwYbtbgkphwI8Y+OfovWBF0ZIPoXBwICX0KHD2USHbmzZe0tR9NnR6ibGgfvW3NK/JiCQDlxmgYvrrhHGScZ3mosU3MZc25/5gY1vEr+MgXaRohXFETUGmsL39oQwA6ZvGrmNU6t8gugfbnxOCgdAQEYcdZXNnaPhtKhyUgl17p2GTTUDOOu+QiJoDmsoKPV65hbE2zlSGTXzA+jEsqeE/4YiQbYlf3dSD2/8n1DKSCwQqUXe25ixxP3a/ZCluXa3CIZWac9t59bXmjmAi0AhWPgtiNaUWuF30nBAz5rzgu3eF6zKd2+wWa4JIHSTDDhj5qb17wOALwnx08iQIMieiAH8JJZt/HxZstOpev/gWy475KoYUzf50VQMgmKi2qtvcEhYZfaDR+HmCw6v7yJ1X8D146Su2i98owWJXNq8jTPDngEktVH4r5TIBoXaGLn28u6PN2ou58JiZFw7EAwEZco2bozirOfFFCKNKA6nv8ZKVVOHFY8KgVe5pfShmrntAL2lvUBVQFciU4gX4mvW8b46E56uD/bY57Z9ETVW0RCU5knmJpJJgUvWE9829sgRcomyB3khCpIOz10WlNYrugQR0cfW4zO+Wfdmymq8Dk9+pSRSAfq6//MJoSfQ603rELuyEIfIH8+/RV0EkjarjdEidM5/pLmlDm0nE/yn98wgNpW+Q+zI7+cxdwIU8SDT4XZEPDVx/UZlkH5nx3xNnkT4ENDM0cc/2mV7wL/Af+/KX5WkoUeSE4LRBGtHdOy8qhMqPY9RQeNXcG/hLVwYm8MKgJl4O2oheLuK4XzHk2ZxocSbvjw/Ia91GY00MQ==,iv:kfNPEar1YfZP9utUw/PQ3Kyn+QSQrDXrcawWaZVlkeE=,tag:F1gNAsiEjlBWdYjx6jdW0A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1va7h9cnqt2gfhvy0pj947wmmewlahvj9j4zyzfznkpp9erf8xawscgft7c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3ais5ZVdINjd5bUFRRkVM
            alJnRnN3OTRDMHVBVU02QVJEZCt6U0hpd21ZCko1NW44RVlMM3VFWURTdloxWldJ
            U2VoMWNmY1JtZnlqTWQxamxZUzNKZ00KLS0tIGZNN0o2TFdNenhpbzlTQlloK0Nq
            TnlOMzI3NXFscCtkUnhtVTJqcmV6UlkKr3pJpIJvi+QISSEOyr3wNwQcC2wRNpiO
            CVBPd3nkdzncBnuCodrmYLvnFg4NFqBOTGVBNtRuK0/Msx1z+fHMQw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-28T01:05:39Z"
    mac: ENC[AES256_GCM,data:atREhezob0ODZIaPLVonlFaTpMPcRTnKDb7BBbw/OMtSbVZhMZ1VQrMrQwPpBWBfPax0cebK/EUZbeyxzYKsu5vdNtCPKNZvxohbsaAIP+wuVvSmWLkHU9ByWOkHeLFQOgobuY7RamuTjdi2kGAEMc85Pa6y+cvJ7On4xy0nRWA=,iv:ljKbx0MbdfeHJITjdO8RujhIDDBtLe7QAM+w/xAXI6E=,tag:G0p6ToFv5jQqxDG1ZN3vMg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|secrets|token|githubTokens?)$
    version: 3.9.4
