apiVersion: v1
kind: Secret
metadata:
    name: kube-actions-runner-values
    namespace: github-runners
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:Cik4GnipY6qwXLjVpjuGgv34JWPq3CU3LPMy7jKwxopEQM/iFXH2nUesjU1Xtf0vWiQMzr0ir+CYhxXh9mGJupMDsSDJ4g+dC9+3AwpbX/bspx0+wGn/ToEqD/KBxXxKJWPp+QDyXaJ6X4aOUBj1WrTN88osJf8SeIlIYxM1NBkS+0Sn4Wouhaiz1OVa+cZezrXhtPHilR3kSP1QovmzPkbIE1EZRbZunSBcCK4xSk1MynjalzcI4EAYHtFpC1Srtq61wAHSu0Gg0FmROfA8bHQNAGR9YtODtmJ82s4DXfqq85PJk5suAxg/C92TCnktsg2890/PedSDKSeBfJkHpxrNdMjJS/cuJO1uA0fA0P++oGPKxOj/B5yn4ccaDjhtYW+PJD/jNoKHJsB+Wcp610EuWSnoibdhKqGxuXMpudpD4nRopUI/k1xW0SzdxsuDIVqPxlBGPU2tInXddOGb8XdauNzWj8/YgdctwsQkZjsccQ1qTHjW86WMUyumcVhOReB8xA5/NX84YBchd+Pf1sIkjJTls4xwTPDnC1/6rs0oJ/yvEsVQRTFH7ZPr4Lkst+hXCWag2nQzXnDohGodMrv1zDvyFyOIWzrscN+2nzxxCHIfc1KYSfw+mMMF7tgdcec5YnD6rj8lZvooZHn55jj+hk5NvVkg4rpzucqjo8wCrd+6Um8KjNfwEb5nkBv7ELWBmrFmbhgp2ZBhzlzlN64MK4tc9Gz0JETdY0nP26QbrTYSn/ZLW8HzKzrMNK79mPWs27I2d6lWlqfQUiDyCalnX4oQTBO89Q2X3ObOE+GRFWbPfk296TxrFdfju23FtpCHbvxLg6+XsclaWs8g4YBI6Q/4Ly6tFP8F,iv:js76FjOzUaBC3ag/870fO0b/mhSTvtmHVg3oYs0zbhM=,tag:q4pcaN2pTDk03oqhnD4Wxw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1va7h9cnqt2gfhvy0pj947wmmewlahvj9j4zyzfznkpp9erf8xawscgft7c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqdlFXSzU1Q2xFUjQrTm13
            blo4QjQvTXVkZzIyZXVwTUR0dlRMWXFSbFU4CkIvZy9JMnhOUUdud1hLaTI0SmY2
            ZWRpcUc1ekVaRDRrTUFQMHFnRW40UFEKLS0tIFRTK2luaVZ1czFRNFk4ZnlEeUQw
            OWdaQStZRXNGMDBuS2JuZUZUenh1VlUKe81MOGDlx0yGEXZpxCwH+pjXJPSlFF5u
            DOiP9JAEu5GBdkoLOpZ2xXc12KHPVuPm17gI0Zzk2Ys+ZTX0lCMolg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-27T12:44:43Z"
    mac: ENC[AES256_GCM,data:bXuL5H0znmolldo8aPZjGXi15Y45kignL4eAIgtNSNVoZ3/5d8w2/AwWrn2xks3Xaj8cvs6e+GlMm6MedI5WALryVluvB8Q3iBQK7CAPbWWsec1nq/tvjPM8rIFajahPr9Cd5hKPtvxgOKKrKzhS5NZ3nHlS1qjiEgIp4YTiax0=,iv:XhbbyVXkcIJ+8kwa+CFC5QgzoF8l1p5X6JW+H7ohIZw=,tag:g2FC1ZU48PqbFn3NjqczAw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|secrets|token|githubTokens?)$
    version: 3.9.4
