apiVersion: ENC[AES256_GCM,data:r9k=,iv:12h63La+BEk7TOgG3fD/hokvlZuj04+1jjQQO51LK9U=,tag:qA+24jiHvYlyfmLsKrS1pw==,type:str]
kind: ENC[AES256_GCM,data:KgIeDMqM,iv:VG54/2QJt5TshL25Li1gLy/eEgqIoFttBMJg5KqwaLY=,tag:Gd68AWCPy13o0HqaLXtncA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:lrpwISLo2FJ7NZyjIM8bLKvKNRWfxZuP4HE=,iv:J5Y23rc6DlvKm6Q1YU/rPPU1LCaP4YNJKn9QNJl3eeY=,tag:FGfpefs4sdpCYi0yC66o1g==,type:str]
    namespace: ENC[AES256_GCM,data:sJlVmxTyoBLuLBbUUrU=,iv:ehqgr1Ou1uMpELkylPMtsrJ6OXtDIrapXvRUGBRGv7o=,tag:Bz31dvnL0vDUb5OuZOK9iQ==,type:str]
type: ENC[AES256_GCM,data:pOd+Nwpd,iv:GJaxfUHkMec7vUjxafafp+EkPAQkzC2WxTX75/kIfTw=,tag:NHyH9x+ZywqOwce1l1uHtw==,type:str]
stringData:
    values.yaml: ENC[AES256_GCM,data:XtQPtnNgFTVg7OuLJmx2x3WY1ck425U3+yXthCgmto2V9dQ3cIcpYnf/oOYFVhIEeXLt7BJ2As9pHxT5g95UvmzUSlsq2yj/jCg+VmTOVXSZwDIT89wGl95Ft0M9LSWBdjbkqmGGGIapcZw4tXctMGhksAb7kPZE1U/uMvKCVt7vUsb/0x/6ej8mMRFaSQVfzrPQch5it8jY+faljgQYh2oxl1GF2bqZTlLTAp0uxtzZH2IivNxMTAoGwCCMlzdyQOSVl9LmLmml35+xAlKH2PfBP1esgxeNiSc+6/+ax7FPIyZoOqm4cfQeQsJl1bc5fTbXdr+b+mKDOxSRN9ECXyfXvdPg1Sh1RufOWWMQxeSFOD5Mafm0Wbtn2R9hfCzT9ucbpHT5WSQSG5DBC/mNHYbweiVv72m6G56v6JttDUgEUFX7frmhmD+QeK1jH4jx64D2x+eQcIkQ/Or5fgcgyIvM5FhamCFN7GaSQDZ4JNg1dmyM3ab6l/WFTp13DEJh8bWrglKXpKhY0JXVCmkt3VUm3lhMfQ53ryJtGIJsKB0FRhAaJWHF4p73Wzi+s7oonXQ/8xWVKVOH/yLQdQxF+bWzqg9QLtrzR8TPm+nl/WRcWMPWBEuhpYusCNWMa6+hZZLU7LBI3KuoWOtTa3y3Oq5cXrbWF7ZIgGuz/IwB/xQI4qxXTOT/O65TM80cABjhB26NDZZ19lHB0VixmcqvI0hdx2QCRjlIhAuVvNJuXK0kk09Z5rfvywEc064PzBPok+OIGPCxww8kVqjogG3K6xjnlwq/LgwdCCLhgqfeUlwXeA8PwEf+ZzGYjZWMivRkbA0/u9sm0PutUnxhqKTteLcRzTYtvbRVzEI9h0QOrlsarzFfOAtiPX++ozqKk3xdXnHAZ1qaMbpK4lxgMVNU8obP/tcd8zhUw8Lxdwa8oSgdAlPYfs5FGGzDKd4I/BxeEn25dILSq//KAmzXvA6XO300oGCDBZYRK+46osxnflLUfwLN8g7s8hXOllJYTW4doUlBOYGVfyxglEz6UdERxuIDaGsgIHNlTS2LGzLjC+J0yoDNhL9z6G2lRLcRnKaxvYT1,iv:p/SaCL7HziqFxQyYLEwNqUwaYLGebTvw3+gJTomBM/0=,tag:Y4f1M/6QFxVlzJHPrMCITA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1va7h9cnqt2gfhvy0pj947wmmewlahvj9j4zyzfznkpp9erf8xawscgft7c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTdm9COE05Zm9odE5JM2Rs
            aTVrRHc4S2d3dmRTZUpkZERnZUJEWm5mR2l3CnFxUDBHS2VJNi9BMHgvdXZUQWU2
            dW4vbDRaaWg4Mlk5OHcyMW9QOFdMdVUKLS0tIDdjS2VHaHRyZy94V05ZSTkyNjJL
            ZXpKTmgwVnFadWNaNnZNT1QzSy84UkkKrWt967S5DY/a1+wufduw9fp9+YiJLfoV
            +Vj5V66pGF3uwfv4Nu4iWpO7/84CDAmHrfqn8o3ZxVydxBcJSFzmAA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-11T03:24:28Z"
    mac: ENC[AES256_GCM,data:54kzpKB5NF+FSbL4+A2RlCJ1M3D8a08UoSFXTd8egpQAqZ/z3HXs/LVdiIlSQJrTe0kW8m8bJksnTsAB22RSSGIA2rVkGS2WPS70S7I1PLNUYqV0KLU/QJv352lfRKOlXGw056jDClyMS6gKuc3WFaQuImdQhzdQbVE9Qh4d0UQ=,iv:pUMS8LtDa+9WAnIUFGANmKAkv4ZeTU5iW4b32q/N64g=,tag:y+voEVTP+xEBp39KZTVrdw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
