apiVersion: v1
kind: Secret
metadata:
    name: kube-actions-runner-values
    namespace: github-runners
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:tLvKclsIjEsVtD2d0GbkDK9MJjXxvPMDiqWjaKODtITdyJnhRDCoEaRf9V7zA22bj8Gsrz5AMmymjqsXDlhF0lOz9YxWFX0dhZAOwEztWyYfWJwN1JqZAANpX0woJBqaHWo4f+i28yReVEEyMzwNFG9ADvKmwvaLiqptPJFAPEyqCgOs4EWgrSlmvP+lPYU5ng12C5eNKoTy+w52duk0jXs0VyhtInNE1snn3U3rjSbFp7RKnZnSKRGmV9iXdtK34x5rCsdIaePcZAFzwchdyX5yNWJCPg0dcOwRLIdqpMyZ/VrL2/Fbnho6FOBi9D0h58jG+rRZHNZKUAP/KYLEZIF3/V8aKxtIfVAL5kDSTY0mmumrFuNOFq58T2Lx9VfJs26fhk8bd4so2X8aC/voI7On+uiubS+q3gUVJqbiD0DGTgeX3mBEyJgBRKseXuvgySVDIspVOSWAmVZ33eVCBAOQZYSNEAIx5q0RfqdjqEaSvoQNriwPhOMNMOZjDxHtadsasps0CUD1V5lCDRb2eLZh28GTL8vzEqDQ8DakTEK/W/YnFS+eyhDTy4K6WKQ/kbPU+CGx9VNEh6R11IwIIoKmbRfFnMmLmkKlUilU9l4NuuBheGFnrg73AuOlF2hmjYm52A6jG/JwvGrzWTzPpG9LEl87NhP+QiC6vNiEIbBmpm0lgonqRSJ5rPSjTAYraUR1wSmZ8un+9DYm2n571yWirby28QJmAAd3OeoYWy/lUV/asS0M63uqDOwIQdyUf+AxmSaGI6ZPU7gLFQwHAvLowKT4tbMAXgmN7TI0nxjbi/aJN/XLI524p6+zwIfGuQlta3bhabiah23054/wrOB8NToZFZYNl9nX2oOhNqN9cDeJfRpUjzhoJLdO4Xwrpc3mYIfqsH5xT6INvgFzv1qH0rBEFGpRGP8AmnFJZL0xunFjmA5o,iv:ktp42t4vx+/qNggoJFP8rouiR8MSVzXgKDU4e9i413Y=,tag:wesQO9NgmlDQohaDOjGNZg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1va7h9cnqt2gfhvy0pj947wmmewlahvj9j4zyzfznkpp9erf8xawscgft7c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvSjZTNnUwNWk0cjh4alVI
            Tnd0RVJwTERFM1k0RTBpVEFOTkt5YXZUTTNRCmRQdVdSYUNpdkUwZDRnRjE5T1FL
            WGxweGFxZ3pWbFhCMWZoYnFxUEZwTEEKLS0tIGgySU1tRUtOWjlNcVdxQS8rQjY3
            b3F0S1VOc0tDaStKNnRiQUxMZTdNRWMKuyWjZDjW/iwBSRiA8JiMWfuhDlAmJLD5
            3+mNSh2FIwSFq7ymZJha1cupQm3mA40qoEJ5puuHpUv0LPfUDEZaRQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-30T16:28:36Z"
    mac: ENC[AES256_GCM,data:5W59+nbeBAWC6I8JtuNQYHL0vZNfze69/NFgHflHQQZgHJv7zd+f6Rl3TPPqYYC0lMDhtCS7OVeOH4tCagA4vAiaTsFm3G5cw0OZu9zjaMSP39ZrocJIoPK3GDYIpIQbTmOQqP1GGtNwVeR3gpGld6DDm0sdojUPmiC5ai5NBLM=,iv:Rv7NizJQ0AH7VOO/B3HKFbzBC2+yYUtF5HqMz87kEUc=,tag:lWonS/Zzx7t1XQVorUYjmw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|secrets|token|githubTokens?)$
    version: 3.8.0
