---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-cloudbox3-config
  namespace: cloudbox-ingress
data:
  nginx.conf: |
    events {}
    stream {
      server {
        listen 80;
        proxy_pass cilium-gateway-cloudbox3-gateway.kube-system.svc.cluster.local:80;
        proxy_connect_timeout 5s;
        proxy_timeout 60s;
      }
      server {
        listen 443;
        proxy_pass cilium-gateway-cloudbox3-gateway.kube-system.svc.cluster.local:443;
        proxy_connect_timeout 5s;
        proxy_timeout 600s;
      }
    }
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nginx-cloudbox3
  namespace: cloudbox-ingress
spec:
  selector:
    matchLabels:
      app: nginx-cloudbox3
  template:
    metadata:
      labels:
        app: nginx-cloudbox3
    spec:
      hostNetwork: true
      dnsPolicy: None
      dnsConfig:
        nameservers:
          - 169.254.20.10
        searches:
          - kube-system.svc.cluster.local
          - svc.cluster.local
          - cluster.local
      tolerations:
        - key: node-role.kubernetes.io/edge
          operator: Exists
          effect: NoSchedule
      nodeSelector:
        kubernetes.io/hostname: cloudbox3
      containers:
        - name: nginx
          image: nginx:stable-alpine
          volumeMounts:
            - name: config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
            limits:
              memory: 64Mi
      volumes:
        - name: config
          configMap:
            name: nginx-cloudbox3-config
